SET 'auto.offset.reset' = 'earliest';
SET 'ksql.variable.substitution.enable' = 'true';

DEFINE SBD_ENV = 'ecasrdev.dev';
DEFINE AGENT='sbd_dev';
DEFINE ZABBIX_EVENTS_TOPIC='Zabbix_events';
DEFINE SERVICE_MONITORING_TOPIC='SERVICE_MONITORING_TEST';
DEFINE HV_FILTERED_TOPIC='HV_FILTER_TEST';
DEFINE TCI_EVENTS_TOPIC='TCI';
DEFINE AGGREGATION_ALERTS_TOPIC='AGGREGATION_ALERTS_TEST';
DEFINE ZABBIX_NQA_PROBES_TOPIC='nqa_raw';
DEFINE S2S_THRESHOLD='10';
DEFINE NQA_PROBES_CPE_THRESHOLD='500';
DEFINE NQA_PROBES_FOS_THRESHOLD='250';
DEFINE NQA_PROBES_INTERNET_THRESHOLD='20';